# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: carpcapture.com
email: info@carpcapture.com
description: > # this means to ignore newlines until "baseurl:"
  Get more carp on the bank with carpcapture app.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carpcapture.com" # the base hostname & protocol for your site
twitter_username: carpcaptureapp
github_username:  carpcapture

# Build settings
markdown: kramdown
